CommonGen data statement
GEM-benchmark/GEM-benchmark.github.io pull request #1
Opened 2020-11-20 22:14 UTC by yjernite

This proposes a first version of a Dataset Sheet for the CommonGen Dataset

2020-12-07 15:22 UTC, salomeyosei approved these changes

2020-12-15 03:06 UTC, yjernite commented
@sebastianGehrmann here's the updated version following the new template!

2020-12-16 18:57 UTC, sebastianGehrmann requested changes
Looking good to me, just a couple small comments.

2020-12-16 18:57 UTC, sebastianGehrmann commented on web/tasks/CommonGen.md
> +If the dataset supports an active leaderboard, add a link here and describe how models are evaluated.
Could you fill this?

2020-12-16 18:57 UTC, sebastianGehrmann commented on web/tasks/CommonGen.md
> +Each example in the dataset consists in a set of 3 to 5 concepts denoted by a single noun, verb, or adjective (the input), and a sentence using these concepts (the output). The dataset provides sever
consists in -> consists of

2020-12-16 18:57 UTC, sebastianGehrmann commented on web/tasks/CommonGen.md
> +No demographic information is provided
nit: end on period

2020-12-16 18:57 UTC, sebastianGehrmann commented on web/tasks/CommonGen.md
> +The dataset does not contain any additional annotations,
nit: period instead of comma

2020-12-16 18:57 UTC, sebastianGehrmann commented on web/tasks/CommonGen.md
> +The language in the development and test set is crowdsourced, which means that it was written by workers whose main goal was speed. This is likely to impact the quality and variety of the targets.
Maybe also note that the population of turkers is not identically distributed as the overall population which may lead to different representation of situations or underlying expectations of what these situations are.

2020-12-17 14:39 UTC, merged